version: '2'
services:
  database:
    container_name: dhis2-database
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      #- ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      #POSTGRES_DB_TARGET: dhis-target
      #PG_DATA: /var/lib/postgresql/data/pgdata:z
    ports:
     - "5432:5432"
  web:
    container_name: dhis2-web
    image: dhis2/core:2.36.4
    volumes:
    - ./conf/dhis.conf:/DHIS2_home/dhis.conf
    - ./conf/hibernate.properties:/DHIS2_home/hibernate.properties
    environment:
      WAIT_FOR_DB_CONTAINER: "database:5432 -t 0"
      JAVA_OPTS: "-Xmx1024m -Xms512m"
      POSTGRES_DB: dhis
    ports:
    - "8085:8080"
    depends_on:
    - database
    #entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    #command: catalina.sh run # https://github.com/docker/compose/issues/3140
